/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apical_cdr_CamCdr */

#ifndef _Included_com_apical_cdr_CamCdr
#define _Included_com_apical_cdr_CamCdr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apical_cdr_CamCdr
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_com_apical_cdr_CamCdr_nativeInit
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     com_apical_cdr_CamCdr
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_apical_cdr_CamCdr_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_apical_cdr_CamCdr
 * Method:    nativeSetPreviewSurface
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_apical_cdr_CamCdr_nativeSetPreviewSurface
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_apical_cdr_CamCdr
 * Method:    nativeSetPreviewTexture
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_apical_cdr_CamCdr_nativeSetPreviewTexture
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_apical_cdr_CamCdr
 * Method:    nativeStartPreview
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_apical_cdr_CamCdr_nativeStartPreview
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_apical_cdr_CamCdr
 * Method:    nativeStopPreview
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_apical_cdr_CamCdr_nativeStopPreview
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
